export const SCORE_VERSION = 1;
export const questions = {
  es: [
    { id:'requests', area:'Solicitudes de huéspedes', question:'Cuando un huésped pide algo a otro departamento, ¿cómo se le da seguimiento?', answers:['De palabra o por mensajes sueltos','Se anota, pero hay que preguntar quién lo atiende','Tiene responsable y estado visibles','Además, se verifica la solución antes de cerrar'], opportunity:'Que ninguna solicitud se pierda entre equipos.', action:'Registra cada solicitud con ubicación, responsable, prioridad y estado hasta verificar su solución.', improve:'Revisa una muestra de cierres cada semana y acuerda qué evidencia demuestra que la solicitud quedó resuelta.', features:['Tareas','Responsables y estados','Ubicaciones','Adjuntos'], metric:'Solicitudes pendientes sin responsable.', template:['Solicitud','Ubicación','Responsable','Prioridad','Estado','Evidencia de solución'] },
    { id:'handover', area:'Cambios de turno', question:'Al cambiar de turno, ¿cómo se entregan los pendientes?', answers:['De palabra','Por mensajes o una lista que requiere contexto','En un registro actualizado con responsables','Con responsables, bloqueos y siguiente acción'], opportunity:'Entregar el turno sin perder el contexto.', action:'Antes del relevo, deja cada pendiente con responsable, prioridad y próxima acción en una vista compartida.', improve:'Revisa en cada relevo los bloqueos y confirma quién toma la próxima acción.', features:['Tableros de tareas','Estados y prioridades','Comentarios','Campos personalizados'], metric:'Pendientes entregados sin responsable o próxima acción.', template:['Pendiente','Área','Turno','Responsable','Bloqueo','Próxima acción'] },
    { id:'rooms', area:'Preparación de habitaciones', question:'¿Cómo confirma supervisión que una habitación terminó su limpieza y está revisada?', answers:['Con una confirmación verbal o un mensaje','Se marca terminada, sin registrar la revisión','Se registra la revisión con criterios definidos','Además, se asignan y verifican las correcciones'], opportunity:'Distinguir una habitación terminada de una revisada.', action:'Define los pasos de limpieza, revisión y corrección, con criterios claros antes del cierre operativo.', improve:'Revisa las observaciones que se repiten y ajusta el checklist con supervisión.', features:['Plantillas','Formularios y checklists','Hallazgos','Aprobaciones'], metric:'Trabajos de limpieza cerrados sin revisión registrada.', template:['Habitación','Limpieza finalizada','Revisor','Observación','Responsable de corrección','Revisión final'], note:'El score evalúa el trabajo operativo. Actualizar el PMS requiere una integración específica.' },
    { id:'maintenance', area:'Mantenimiento preventivo', question:'¿Cómo se asegura el hotel de que el mantenimiento preventivo se haga a tiempo?', answers:['Se actúa principalmente cuando algo falla','Hay un calendario con recordatorios manuales','Hay actividades programadas y responsables','Además, se revisa la ejecución y lo pendiente'], opportunity:'Dar continuidad al mantenimiento preventivo.', action:'Empieza con un plan de trabajo para un equipo o área prioritaria: frecuencia, responsable y registro de ejecución.', improve:'Revisa actividades pendientes y ajusta la programación según las necesidades observadas.', features:['Planes de trabajo','Tareas recurrentes','Ubicaciones','Evidencias'], metric:'Actividades preventivas vencidas en el período.', template:['Equipo o área','Actividad','Frecuencia','Fecha prevista','Responsable','Fecha de ejecución'] },
    { id:'timing', area:'Tiempos de atención', question:'¿Cómo controla el hotel cuánto tarda en atender y resolver una incidencia?', answers:['No hay tiempos definidos','Hay expectativas, pero no se revisan con frecuencia','Hay plazos por tipo de incidencia y se revisan','Además, se analizan las causas de los atrasos'], opportunity:'Dar un significado claro a «a tiempo».', action:'Define objetivos de respuesta y resolución por tipo de trabajo y revisa primero los que afectan al huésped.', improve:'Analiza los incumplimientos recurrentes y acuerda una acción sobre su causa.', features:['SLAs','Prioridades','Tareas','Vistas de seguimiento'], metric:'Incidencias fuera del plazo acordado.', template:['Tipo de incidencia','Prioridad','Objetivo de respuesta','Objetivo de resolución','Responsable','Motivo de atraso'], note:'Los avisos y escalamientos automáticos requieren configurar y validar su ejecución.' },
    { id:'findings', area:'Inspecciones y hallazgos', question:'Cuando una inspección detecta un problema, ¿qué sucede después?', answers:['Se comunica, pero puede quedar sin seguimiento','Se anota, a veces sin responsable o fecha','Se asigna una acción y se sigue hasta resolverla','Además, se verifica la corrección antes de cerrar'], opportunity:'Convertir las inspecciones en correcciones verificables.', action:'Asigna cada hallazgo que necesite atención, define una fecha y registra cómo se comprobará la corrección.', improve:'Revisa los hallazgos repetidos y ajusta el procedimiento que los está originando.', features:['Hallazgos','Formularios','Tareas y fechas','Adjuntos y estados'], metric:'Hallazgos vencidos o cerrados sin verificación.', template:['Hallazgo','Ubicación','Acción correctiva','Responsable','Fecha límite','Verificación'] },
    { id:'procedures', area:'Procedimientos', question:'Cuando alguien necesita saber cómo realizar una tarea, ¿dónde consulta el procedimiento?', answers:['Pregunta a alguien con experiencia','Busca en carpetas o mensajes','Tiene una fuente organizada y accesible','Lo encuentra junto a la tarea o ubicación'], opportunity:'Poner el procedimiento donde se necesita.', action:'Organiza los procedimientos más consultados y relaciónalos con las tareas o ubicaciones correspondientes.', improve:'Revisa con el equipo si las guías son claras y actualiza los pasos que generan dudas.', features:['Normas y Documentos','Plantillas','Tipos de tarea','Ubicaciones'], metric:'Tareas frecuentes sin un procedimiento accesible.', template:['Procedimiento','Tarea o ubicación','Responsable de revisión','Última revisión','Enlace','Duda por resolver'] },
    { id:'approvals', area:'Aprobaciones', question:'Cuando una tarea necesita autorización, ¿cómo se sigue la decisión?', answers:['Hay que averiguar quién debe aprobar','Se pide y se sigue por mensajes','Hay aprobador y decisión registrados','Además, están claros todos los pasos y participantes'], opportunity:'Hacer visibles las autorizaciones pendientes.', action:'Elige una autorización frecuente y define quién decide, en qué momento y con qué información.', improve:'Revisa dónde se acumulan autorizaciones y aclara criterios o pasos que generan devoluciones.', features:['Aprobaciones','Aprobadores y secuencias','Tareas','Adjuntos'], metric:'Solicitudes pendientes de aprobación sin siguiente paso claro.', template:['Solicitud','Información necesaria','Aprobador','Fecha de solicitud','Decisión','Siguiente paso'] },
    { id:'reporting', area:'Reportes desde el lugar de trabajo', question:'Al recibir una avería, ¿con qué frecuencia hay que pedir más información antes de actuar?', answers:['Casi siempre: faltan datos básicos','Con frecuencia: cada persona reporta diferente','Pocas veces: usamos un formato común','Casi nunca: incluye datos y evidencias pertinentes'], opportunity:'Recibir la información necesaria desde el principio.', action:'Define los datos de cada tipo de reporte y facilita su captura junto al equipo o área donde ocurre.', improve:'Identifica las preguntas que todavía se repiten y ajusta los campos del reporte.', features:['Formularios','Campos personalizados','Ubicaciones','Adjuntos'], metric:'Reportes devueltos por información incompleta.', template:['Ubicación','Equipo','Descripción','Prioridad','Evidencia','Dato adicional necesario'], note:'Puedes complementar el acceso con un enlace NFC preparado para ese punto, probando dispositivo y permisos.' },
    { id:'visibility', area:'Visibilidad para gerencia', question:'Si gerencia necesita conocer los pendientes y atrasos de cada área, ¿cómo obtiene esa información?', answers:['Pregunta a varios responsables','Alguien prepara un reporte manual','Consulta una vista compartida y actualizada','Además, revisa indicadores y acuerda mejoras'], opportunity:'Usar la información para decidir.', action:'Configura una vista con pendientes, vencidos y avance por área, y establece una revisión periódica.', improve:'Relaciona cada indicador con una decisión, un responsable y una fecha de revisión.', features:['Dashboards','KPIs','Filtros','Vistas de tareas'], metric:'Acciones de mejora acordadas y revisadas en el período.', template:['Indicador','Área','Período','Resultado','Acción acordada','Responsable','Fecha de revisión'] },
  ],
  en: [
    { id:'requests', area:'Guest requests', question:'When a guest needs something from another department, how is it followed through?', answers:['Verbally or through scattered messages','Logged, but someone must ask who is handling it','An owner and status are visible','The solution is also verified before closing'], opportunity:'Keep requests from getting lost between teams.', action:'Log each request with a location, owner, priority and status until the solution is verified.', improve:'Review a sample of closures weekly and agree what evidence confirms resolution.', features:['Tasks','Owners and statuses','Locations','Attachments'], metric:'Open requests without an owner.', template:['Request','Location','Owner','Priority','Status','Resolution evidence'] },
    { id:'handover', area:'Shift handovers', question:'At a shift change, how are outstanding tasks handed over?', answers:['Verbally','Through messages or a list needing context','In an updated record with owners','With owners, blockers and next actions'], opportunity:'Keep the context across shifts.', action:'Before handover, give each open item an owner, priority and next action in a shared view.', improve:'Review blockers at every handover and confirm who owns the next action.', features:['Task boards','Statuses and priorities','Comments','Custom fields'], metric:'Handed-over items without an owner or next action.', template:['Open item','Area','Shift','Owner','Blocker','Next action'] },
    { id:'rooms', area:'Room readiness', question:'How does supervision confirm that a room has been cleaned and inspected?', answers:['With a verbal confirmation or message','Marked complete without a recorded inspection','An inspection is recorded against clear criteria','Corrections are also assigned and verified'], opportunity:'Distinguish completed work from inspected work.', action:'Define cleaning, inspection and correction steps with clear criteria before operational closure.', improve:'Review repeated observations and adjust the checklist with supervisors.', features:['Templates','Forms and checklists','Findings','Approvals'], metric:'Cleaning tasks closed without a recorded inspection.', template:['Room','Cleaning completed','Inspector','Observation','Correction owner','Final inspection'], note:'This assesses operational work. Updating the PMS requires a specific integration.' },
    { id:'maintenance', area:'Preventive maintenance', question:'How does the hotel keep preventive maintenance on schedule?', answers:['Work mainly starts when something breaks','A calendar relies on manual reminders','Activities are scheduled with owners','Completion and outstanding work are also reviewed'], opportunity:'Keep preventive maintenance moving.', action:'Start a work plan for one priority asset or area with frequency, ownership and execution records.', improve:'Review outstanding activities and adjust scheduling to observed needs.', features:['Work plans','Recurring tasks','Locations','Evidence'], metric:'Overdue preventive activities in the period.', template:['Asset or area','Activity','Frequency','Planned date','Owner','Completion date'] },
    { id:'timing', area:'Service response times', question:'How does the hotel control the time it takes to respond to and resolve an issue?', answers:['There are no defined targets','There are expectations but little regular review','Targets differ by issue type and are reviewed','Causes of delays are also analyzed'], opportunity:'Give “on time” a shared meaning.', action:'Set response and resolution targets by work type, starting with guest-facing issues.', improve:'Analyze repeated missed targets and agree an action on the cause.', features:['SLAs','Priorities','Tasks','Tracking views'], metric:'Issues outside the agreed time target.', template:['Issue type','Priority','Response target','Resolution target','Owner','Reason for delay'], note:'Automatic notifications and escalations require configuration and execution validation.' },
    { id:'findings', area:'Inspections and findings', question:'When an inspection identifies a problem, what happens next?', answers:['It is communicated but may not be tracked','Logged, sometimes without an owner or date','An action is assigned and tracked to resolution','The correction is also verified before closure'], opportunity:'Turn inspections into verified corrections.', action:'Assign each finding that needs attention, set a date and record how the correction will be checked.', improve:'Review repeated findings and adjust the procedure behind them.', features:['Findings','Forms','Tasks and dates','Attachments and statuses'], metric:'Findings overdue or closed without verification.', template:['Finding','Location','Corrective action','Owner','Due date','Verification'] },
    { id:'procedures', area:'Procedures', question:'When someone needs to know how to do a task, where do they find the procedure?', answers:['They ask an experienced colleague','They search folders or messages','An organized source is accessible','It is linked to the task or location'], opportunity:'Put procedures where they are needed.', action:'Organize frequently used procedures and relate them to the relevant tasks or locations.', improve:'Check with the team whether guides are clear and update confusing steps.', features:['Standards and Documents','Templates','Task types','Locations'], metric:'Frequent tasks without an accessible procedure.', template:['Procedure','Task or location','Review owner','Last review','Link','Question to resolve'] },
    { id:'approvals', area:'Approvals', question:'When a task needs authorization, how is the decision tracked?', answers:['Someone must find out who can approve','Requested and followed up through messages','The approver and decision are recorded','All steps and participants are also clear'], opportunity:'Make pending authorizations visible.', action:'Choose a frequent authorization and define who decides, when and with what information.', improve:'Review approval backlogs and clarify criteria or steps that cause rework.', features:['Approvals','Approvers and sequences','Tasks','Attachments'], metric:'Pending approvals without a clear next step.', template:['Request','Required information','Approver','Request date','Decision','Next step'] },
    { id:'reporting', area:'On-site reporting', question:'When a fault is reported, how often do you need more information before acting?', answers:['Almost always: basic details are missing','Often: everyone reports differently','Rarely: we use a common format','Almost never: relevant details and evidence are included'], opportunity:'Get the information needed from the start.', action:'Define the details needed for each report type and make capture easy at the asset or area.', improve:'Identify recurring follow-up questions and adjust report fields.', features:['Forms','Custom fields','Locations','Attachments'], metric:'Reports returned because information is incomplete.', template:['Location','Asset','Description','Priority','Evidence','Additional information needed'], note:'An NFC link can provide access at the work point, after checking device compatibility and permissions.' },
    { id:'visibility', area:'Management visibility', question:'How does management find outstanding and overdue work across departments?', answers:['By asking several managers','Someone compiles a manual report','Through an updated shared view','Indicators are also reviewed and improvements agreed'], opportunity:'Use the information to make decisions.', action:'Set up a view of open, overdue and completed work by area and review it regularly.', improve:'Connect each indicator to a decision, owner and review date.', features:['Dashboards','KPIs','Filters','Task views'], metric:'Improvement actions agreed and reviewed in the period.', template:['Indicator','Area','Period','Result','Agreed action','Owner','Review date'] },
  ],
};

export function validAnswers(answers) {
  return Array.isArray(answers) && answers.length === 10 && answers.every(v => (Number.isInteger(v) && v >= 0 && v <= 3) || v === 'unknown' || v === 'na');
}
export function calculateScore(answers) {
  if (!validAnswers(answers)) throw new Error('Invalid score answers');
  const evaluated = answers.filter(v => typeof v === 'number');
  const score = evaluated.length ? Math.round(evaluated.reduce((sum, v) => sum + v, 0) / (evaluated.length * 3) * 100) : null;
  const indices = answers.map((_, i) => i);
  return {
    score, evaluated: evaluated.length, partial: evaluated.length < 6,
    level: score === null ? null : score < 25 ? 0 : score < 50 ? 1 : score < 75 ? 2 : 3,
    opportunities: indices.filter(i => typeof answers[i] === 'number' && answers[i] < 3).sort((a,b) => answers[a] - answers[b] || a - b).slice(0,3),
    strengths: indices.filter(i => answers[i] === 3), unknown: indices.filter(i => answers[i] === 'unknown'),
  };
}
