// Shared copy for the first-day scenes, with the app's labels per language.
export const COMMON = {
  en: {
    brand: 'Hotel Costa Azul',
    everything: 'Everything',
    spacesLbl: 'Spaces',
    spaces: ['Maintenance', 'Housekeeping', 'Front Office'],
    tasksTitle: 'Maintenance · Tasks',
    cols: ['ID', 'Name', 'Spot', 'Status', 'Assignee'],
    statuses: { pending: 'Pending', progress: 'In Progress', inspecting: 'Inspecting', done: 'Completed' },
    filters: 'Filters',
    assignee: 'Assignee',
    apply: 'Apply',
    you: 'Ana Morales',
    others: ['Jorge Pérez', 'Sofía Vidal', 'Luis Ramos'],
    createTask: 'Create Task',
    createTitle: 'Create New Task',
    name: 'Name',
    spot: 'Spot',
    noSpot: 'No spot',
    attachments: 'Attachments',
    drop: 'Drop files here or click to attach',
    cancel: 'Cancel',
    newTask: 'Replace leaking tap · Room 214',
    room: 'Room 214',
    tasks: [
      ['Replace leaking tap', 'Rm 214'], ['AC not cooling', 'Rm 305'], ['Repaint corridor', 'Floor 2'], ['Check pool pump', 'Pool'],
      ['Fix door closer', 'Rm 118'], ['Replace lobby bulbs', 'Lobby'], ['Unclog shower drain', 'Rm 402'], ['Inspect fire extinguishers', 'Floor 1'],
    ],
  },
  es: {
    brand: 'Hotel Costa Azul',
    everything: 'Todo',
    spacesLbl: 'Espacios',
    spaces: ['Mantenimiento', 'Ama de llaves', 'Recepción'],
    tasksTitle: 'Mantenimiento · Tareas',
    cols: ['ID', 'Nombre', 'Spot', 'Estado', 'Asignado'],
    statuses: { pending: 'Pendiente', progress: 'En progreso', inspecting: 'Inspección', done: 'Completada' },
    filters: 'Filtros',
    assignee: 'Asignado',
    apply: 'Aplicar',
    you: 'Ana Morales',
    others: ['Jorge Pérez', 'Sofía Vidal', 'Luis Ramos'],
    createTask: 'Crear Tarea',
    createTitle: 'Crear Nueva Tarea',
    name: 'Nombre',
    spot: 'Spot',
    noSpot: 'Sin spot',
    attachments: 'Adjuntos',
    drop: 'Arrastra archivos aquí o haz clic para adjuntar',
    cancel: 'Cancelar',
    newTask: 'Cambiar llave que gotea · Hab 214',
    room: 'Hab 214',
    tasks: [
      ['Cambiar llave que gotea', 'Hab 214'], ['Aire acondicionado no enfría', 'Hab 305'], ['Pintar pasillo', 'Piso 2'], ['Revisar bomba de alberca', 'Alberca'],
      ['Arreglar cierrapuertas', 'Hab 118'], ['Cambiar focos del lobby', 'Lobby'], ['Destapar coladera', 'Hab 402'], ['Revisar extintores', 'Piso 1'],
    ],
  },
  pt: {
    brand: 'Hotel Costa Azul',
    everything: 'Tudo',
    spacesLbl: 'Espaços',
    spaces: ['Manutenção', 'Governança', 'Recepção'],
    tasksTitle: 'Manutenção · Tarefas',
    cols: ['ID', 'Nome', 'Spot', 'Status', 'Responsável'],
    statuses: { pending: 'Pendente', progress: 'Em andamento', inspecting: 'Inspeção', done: 'Concluída' },
    filters: 'Filtros',
    assignee: 'Responsável',
    apply: 'Aplicar',
    you: 'Ana Morales',
    others: ['Jorge Pérez', 'Sofía Vidal', 'Luis Ramos'],
    createTask: 'Criar tarefa',
    createTitle: 'Criar nova tarefa',
    name: 'Nome',
    spot: 'Spot',
    noSpot: 'Sem spot',
    attachments: 'Anexos',
    drop: 'Arraste arquivos aqui ou clique para anexar',
    cancel: 'Cancelar',
    newTask: 'Trocar torneira pingando · Qto 214',
    room: 'Quarto 214',
    tasks: [
      ['Trocar torneira pingando', 'Qto 214'], ['Ar-condicionado não gela', 'Qto 305'], ['Pintar corredor', 'Andar 2'], ['Verificar bomba da piscina', 'Piscina'],
      ['Consertar mola da porta', 'Qto 118'], ['Trocar lâmpadas do lobby', 'Lobby'], ['Desentupir ralo do box', 'Qto 402'], ['Inspecionar extintores', 'Andar 1'],
    ],
  },
  de: {
    brand: 'Hotel Costa Azul',
    everything: 'Alles',
    spacesLbl: 'Bereiche',
    spaces: ['Technik', 'Housekeeping', 'Rezeption'],
    tasksTitle: 'Technik · Aufgaben',
    cols: ['ID', 'Name', 'Spot', 'Status', 'Zugewiesen'],
    statuses: { pending: 'Offen', progress: 'In Arbeit', inspecting: 'Prüfung', done: 'Erledigt' },
    filters: 'Filter',
    assignee: 'Zugewiesene Person',
    apply: 'Anwenden',
    you: 'Ana Morales',
    others: ['Jorge Pérez', 'Sofía Vidal', 'Luis Ramos'],
    createTask: 'Create Task',
    createTitle: 'Create New Task',
    name: 'Name',
    spot: 'Spot',
    noSpot: 'Kein Spot',
    attachments: 'Anhänge',
    drop: 'Dateien hier ablegen oder klicken, um anzuhängen',
    cancel: 'Abbrechen',
    newTask: 'Tropfenden Hahn tauschen · Zi. 214',
    room: 'Zimmer 214',
    tasks: [
      ['Tropfenden Hahn tauschen', 'Zi. 214'], ['Klimaanlage kühlt nicht', 'Zi. 305'], ['Flur streichen', '2. OG'], ['Poolpumpe prüfen', 'Pool'],
      ['Türschließer reparieren', 'Zi. 118'], ['Lobbylampen tauschen', 'Lobby'], ['Duschablauf freimachen', 'Zi. 402'], ['Feuerlöscher prüfen', '1. OG'],
    ],
  },
};

export function withCommon(own) {
  return Object.fromEntries(Object.keys(COMMON).map((lang) => [lang, { ...COMMON[lang], ...own[lang] }]));
}
