// Shared copy for the approvals scenes. UI labels follow the app's own
// translations; where the German or Portuguese app still shows English for a
// setting, the scene shows the same English so it matches the screen.
export const COMMON = {
  en: {
    space: 'Maintenance · Tasks',
    cols: ['ID', 'Name', 'Spot', 'Status', 'Assignee'],
    statuses: { pending: 'Pending', progress: 'In Progress', approved: 'Approved to buy', done: 'Completed' },
    request: 'Purchase request · 2 mattresses',
    rows: [['Replace leaking tap', 'Rm 214'], ['AC not cooling', 'Rm 305'], ['Repaint corridor', 'Floor 2'], ['Check pool pump', 'Pool']],
    room: 'Rm 412',
    approval: 'Purchase over $500',
    approver: 'Laura Méndez',
    approverRole: 'Head of Housekeeping',
    progress: 'Approval progress',
    pendingLbl: 'Pending',
    approvedLbl: 'Approved',
    rejectedLbl: 'Rejected',
    approve: 'Approve',
    reject: 'Reject',
    approvedWord: 'approved',
    tag: 'Needs changes',
  },
  es: {
    space: 'Mantenimiento · Tareas',
    cols: ['ID', 'Nombre', 'Spot', 'Estado', 'Asignado'],
    statuses: { pending: 'Pendiente', progress: 'En progreso', approved: 'Aprobada para comprar', done: 'Completada' },
    request: 'Solicitud de compra · 2 colchones',
    rows: [['Cambiar llave que gotea', 'Hab 214'], ['Aire acondicionado no enfría', 'Hab 305'], ['Pintar pasillo', 'Piso 2'], ['Revisar bomba de alberca', 'Alberca']],
    room: 'Hab 412',
    approval: 'Compra mayor a $500',
    approver: 'Laura Méndez',
    approverRole: 'Jefa de ama de llaves',
    progress: 'Progreso de aprobación',
    pendingLbl: 'Pendiente',
    approvedLbl: 'Aprobado',
    rejectedLbl: 'Rechazado',
    approve: 'Aprobar',
    reject: 'Rechazar',
    approvedWord: 'aprobó',
    tag: 'Requiere cambios',
  },
  pt: {
    space: 'Manutenção · Tarefas',
    cols: ['ID', 'Nome', 'Spot', 'Status', 'Responsável'],
    statuses: { pending: 'Pendente', progress: 'Em andamento', approved: 'Aprovado para compra', done: 'Concluída' },
    request: 'Pedido de compra · 2 colchões',
    rows: [['Trocar torneira pingando', 'Qto 214'], ['Ar-condicionado não gela', 'Qto 305'], ['Pintar corredor', 'Andar 2'], ['Verificar bomba da piscina', 'Piscina']],
    room: 'Qto 412',
    approval: 'Compra acima de R$ 2.500',
    approver: 'Laura Méndez',
    approverRole: 'Chefe de governança',
    progress: 'Progresso da aprovação',
    pendingLbl: 'Pendente',
    approvedLbl: 'Aprovado',
    rejectedLbl: 'Rejeitado',
    approve: 'Aprovar',
    reject: 'Rejeitar',
    approvedWord: 'aprovou',
    tag: 'Precisa de ajustes',
  },
  de: {
    space: 'Technik · Aufgaben',
    cols: ['ID', 'Name', 'Spot', 'Status', 'Zugewiesen'],
    statuses: { pending: 'Offen', progress: 'In Arbeit', approved: 'Kauf freigegeben', done: 'Erledigt' },
    request: 'Bestellanforderung · 2 Matratzen',
    rows: [['Tropfenden Hahn tauschen', 'Zi. 214'], ['Klimaanlage kühlt nicht', 'Zi. 305'], ['Flur streichen', '2. OG'], ['Poolpumpe prüfen', 'Pool']],
    room: 'Zi. 412',
    approval: 'Einkauf über 500 €',
    approver: 'Laura Méndez',
    approverRole: 'Hausdamenleitung',
    progress: 'Genehmigungsfortschritt',
    pendingLbl: 'Ausstehend',
    approvedLbl: 'Genehmigt',
    rejectedLbl: 'Abgelehnt',
    approve: 'Genehmigen',
    reject: 'Ablehnen',
    approvedWord: 'hat genehmigt',
    tag: 'Nachbessern',
  },
};

/** Merge the shared copy with a scene's own strings, per language. */
export function withCommon(own) {
  return Object.fromEntries(Object.keys(COMMON).map((lang) => [lang, { ...COMMON[lang], ...own[lang] }]));
}
